[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "koi-net-debug-node"
version = "1.0.0"
description = "Implementation of KOI-net debug node in Python"
authors = [
    {name = "Luke Miller", email = "luke@block.science"}
]
readme = "README.md"
requires-python = ">=3.10"
# license = {file = "LICENSE"}
dependencies = [
    "koi-net~=1.1",
    "slack_bolt>=1.26.0",
    "rich"
]

[project.optional-dependencies]
dev = ["twine>=6.0", "build"]

[project.urls]
Homepage = "https://github.com/BlockScience/koi-net-debug-node/"